var tal1 = 10;
var tal2 = 6;
console.log(tal1 + tal2);
console.log(tal1 - tal2);
console.log(tal1 * tal2);
console.log(tal1 / tal2);
console.log(tal1 % tal2);
tal1++;
console.log(tal1);
tal2--;
console.log(tal2);
